# Generated by Django 4.1.3 on 2022-11-23 21:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Course Category')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Category Image')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('duration', models.DurationField(verbose_name='Course Duration')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Room Image')),
                ('feature', models.BooleanField(verbose_name='Courese type')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_no', models.IntegerField(verbose_name='Chapter No')),
                ('description', models.TextField(verbose_name='Objectives of the Lesson')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='Lesson Video')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='file/', verbose_name='Lesson Pdf')),
                ('feature', models.BooleanField(default=True, verbose_name='lesson Type')),
            ],
        ),
        migrations.CreateModel(
            name='Attending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.course', verbose_name='Building')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.student', verbose_name='Student')),
            ],
        ),
    ]
