# Generated by Django 4.1.3 on 2022-12-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attending',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
