# Generated by Django 4.1.3 on 2022-12-03 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_course_alter_course_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.category', verbose_name='Category'),
        ),
    ]
