# Generated by Django 4.1.3 on 2022-12-23 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_attending_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attending',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='courses.payment', verbose_name='Payment'),
        ),
    ]
