# Generated by Django 4.1.3 on 2022-12-15 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_payment_attending_status_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attending',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.course', verbose_name='Course'),
        ),
    ]
