# Generated by Django 4.1.3 on 2022-12-16 08:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_attending_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_name',
            field=models.CharField(default='g', max_length=50, verbose_name='Bank Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_reference_number',
            field=models.CharField(default='2', max_length=50, verbose_name='Bank Reference Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='course_order_id',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='courses.attending', verbose_name='Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default='2', max_length=100, verbose_name='Transaction Id'),
            preserve_default=False,
        ),
    ]
