# Generated by Django 4.1.3 on 2022-12-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='security_answer',
            field=models.CharField(default='', max_length=50, verbose_name='Sequrity Answer'),
        ),
        migrations.AddField(
            model_name='student',
            name='security_question',
            field=models.CharField(default='', max_length=50, verbose_name='Sequrity Question'),
        ),
    ]
