# Generated by Django 4.1.3 on 2022-12-03 09:58

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_student_security_answer_student_security_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[authentication.models.only_int]),
        ),
    ]
